import { NextRequest, NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";
import auth from "@/lib/auth-server";

const prisma = new PrismaClient();

// 默认省市经度数据（351个城市，覆盖全国34个省级行政区所有地级市）
const DEFAULT_CITIES = [
  { province: "北京市", city: "北京", longitude: 116.4 },
  { province: "天津市", city: "天津", longitude: 117.2 },
  { province: "河北省", city: "石家庄", longitude: 114.48 },
  { province: "河北省", city: "唐山", longitude: 118.02 },
  { province: "河北省", city: "秦皇岛", longitude: 119.6 },
  { province: "河北省", city: "邯郸", longitude: 114.47 },
  { province: "河北省", city: "邢台", longitude: 114.5 },
  { province: "河北省", city: "保定", longitude: 115.46 },
  { province: "河北省", city: "张家口", longitude: 114.87 },
  { province: "河北省", city: "承德", longitude: 117.93 },
  { province: "河北省", city: "沧州", longitude: 116.83 },
  { province: "河北省", city: "廊坊", longitude: 116.7 },
  { province: "河北省", city: "衡水", longitude: 115.67 },
  { province: "山西省", city: "太原", longitude: 112.53 },
  { province: "山西省", city: "大同", longitude: 113.29 },
  { province: "山西省", city: "阳泉", longitude: 113.58 },
  { province: "山西省", city: "长治", longitude: 113.11 },
  { province: "山西省", city: "晋城", longitude: 112.85 },
  { province: "山西省", city: "朔州", longitude: 112.43 },
  { province: "山西省", city: "晋中", longitude: 112.75 },
  { province: "山西省", city: "运城", longitude: 111.0 },
  { province: "山西省", city: "忻州", longitude: 112.73 },
  { province: "山西省", city: "临汾", longitude: 111.52 },
  { province: "山西省", city: "吕梁", longitude: 111.13 },
  { province: "内蒙古自治区", city: "呼和浩特", longitude: 111.65 },
  { province: "内蒙古自治区", city: "包头", longitude: 109.82 },
  { province: "内蒙古自治区", city: "乌海", longitude: 106.82 },
  { province: "内蒙古自治区", city: "赤峰", longitude: 118.89 },
  { province: "内蒙古自治区", city: "通辽", longitude: 122.27 },
  { province: "内蒙古自治区", city: "鄂尔多斯", longitude: 109.77 },
  { province: "内蒙古自治区", city: "呼伦贝尔", longitude: 119.77 },
  { province: "内蒙古自治区", city: "巴彦淖尔", longitude: 107.39 },
  { province: "内蒙古自治区", city: "乌兰察布", longitude: 113.12 },
  { province: "内蒙古自治区", city: "兴安盟", longitude: 122.07 },
  { province: "内蒙古自治区", city: "锡林郭勒", longitude: 116.09 },
  { province: "内蒙古自治区", city: "阿拉善", longitude: 105.68 },
  { province: "辽宁省", city: "沈阳", longitude: 123.43 },
  { province: "辽宁省", city: "大连", longitude: 121.62 },
  { province: "辽宁省", city: "鞍山", longitude: 122.99 },
  { province: "辽宁省", city: "抚顺", longitude: 123.92 },
  { province: "辽宁省", city: "本溪", longitude: 123.77 },
  { province: "辽宁省", city: "丹东", longitude: 124.36 },
  { province: "辽宁省", city: "锦州", longitude: 121.13 },
  { province: "辽宁省", city: "营口", longitude: 122.23 },
  { province: "辽宁省", city: "阜新", longitude: 121.65 },
  { province: "辽宁省", city: "辽阳", longitude: 123.17 },
  { province: "辽宁省", city: "盘锦", longitude: 122.07 },
  { province: "辽宁省", city: "铁岭", longitude: 123.84 },
  { province: "辽宁省", city: "朝阳", longitude: 120.46 },
  { province: "辽宁省", city: "葫芦岛", longitude: 120.86 },
  { province: "吉林省", city: "长春", longitude: 125.32 },
  { province: "吉林省", city: "吉林", longitude: 126.55 },
  { province: "吉林省", city: "四平", longitude: 124.37 },
  { province: "吉林省", city: "辽源", longitude: 125.15 },
  { province: "吉林省", city: "通化", longitude: 125.94 },
  { province: "吉林省", city: "白山", longitude: 126.42 },
  { province: "吉林省", city: "松原", longitude: 124.82 },
  { province: "吉林省", city: "白城", longitude: 122.84 },
  { province: "吉林省", city: "延吉", longitude: 129.51 },
  { province: "黑龙江省", city: "哈尔滨", longitude: 126.53 },
  { province: "黑龙江省", city: "齐齐哈尔", longitude: 123.93 },
  { province: "黑龙江省", city: "鸡西", longitude: 130.97 },
  { province: "黑龙江省", city: "鹤岗", longitude: 130.28 },
  { province: "黑龙江省", city: "双鸭山", longitude: 131.16 },
  { province: "黑龙江省", city: "大庆", longitude: 125.03 },
  { province: "黑龙江省", city: "伊春", longitude: 128.9 },
  { province: "黑龙江省", city: "佳木斯", longitude: 130.37 },
  { province: "黑龙江省", city: "七台河", longitude: 131.01 },
  { province: "黑龙江省", city: "牡丹江", longitude: 129.62 },
  { province: "黑龙江省", city: "黑河", longitude: 127.5 },
  { province: "黑龙江省", city: "绥化", longitude: 126.99 },
  { province: "黑龙江省", city: "大兴安岭", longitude: 124.12 },
  { province: "上海市", city: "上海", longitude: 121.47 },
  { province: "江苏省", city: "南京", longitude: 118.78 },
  { province: "江苏省", city: "无锡", longitude: 120.29 },
  { province: "江苏省", city: "徐州", longitude: 117.18 },
  { province: "江苏省", city: "常州", longitude: 119.97 },
  { province: "江苏省", city: "苏州", longitude: 120.62 },
  { province: "江苏省", city: "南通", longitude: 120.86 },
  { province: "江苏省", city: "连云港", longitude: 119.16 },
  { province: "江苏省", city: "淮安", longitude: 119.03 },
  { province: "江苏省", city: "盐城", longitude: 120.14 },
  { province: "江苏省", city: "扬州", longitude: 119.42 },
  { province: "江苏省", city: "镇江", longitude: 119.44 },
  { province: "江苏省", city: "泰州", longitude: 119.91 },
  { province: "江苏省", city: "宿迁", longitude: 118.3 },
  { province: "浙江省", city: "杭州", longitude: 120.19 },
  { province: "浙江省", city: "宁波", longitude: 121.55 },
  { province: "浙江省", city: "温州", longitude: 120.7 },
  { province: "浙江省", city: "嘉兴", longitude: 120.76 },
  { province: "浙江省", city: "湖州", longitude: 120.1 },
  { province: "浙江省", city: "绍兴", longitude: 120.58 },
  { province: "浙江省", city: "金华", longitude: 119.65 },
  { province: "浙江省", city: "衢州", longitude: 118.87 },
  { province: "浙江省", city: "舟山", longitude: 122.2 },
  { province: "浙江省", city: "台州", longitude: 121.42 },
  { province: "浙江省", city: "丽水", longitude: 119.92 },
  { province: "安徽省", city: "合肥", longitude: 117.28 },
  { province: "安徽省", city: "芜湖", longitude: 118.37 },
  { province: "安徽省", city: "蚌埠", longitude: 117.38 },
  { province: "安徽省", city: "淮南", longitude: 117.0 },
  { province: "安徽省", city: "马鞍山", longitude: 118.51 },
  { province: "安徽省", city: "淮北", longitude: 116.8 },
  { province: "安徽省", city: "铜陵", longitude: 117.81 },
  { province: "安徽省", city: "安庆", longitude: 117.06 },
  { province: "安徽省", city: "黄山", longitude: 118.33 },
  { province: "安徽省", city: "滁州", longitude: 118.32 },
  { province: "安徽省", city: "阜阳", longitude: 115.82 },
  { province: "安徽省", city: "宿州", longitude: 116.98 },
  { province: "安徽省", city: "六安", longitude: 116.51 },
  { province: "安徽省", city: "亳州", longitude: 115.78 },
  { province: "安徽省", city: "池州", longitude: 117.49 },
  { province: "安徽省", city: "宣城", longitude: 118.76 },
  { province: "福建省", city: "福州", longitude: 119.3 },
  { province: "福建省", city: "厦门", longitude: 118.09 },
  { province: "福建省", city: "莆田", longitude: 119.0 },
  { province: "福建省", city: "三明", longitude: 117.64 },
  { province: "福建省", city: "泉州", longitude: 118.58 },
  { province: "福建省", city: "漳州", longitude: 117.65 },
  { province: "福建省", city: "南平", longitude: 118.1 },
  { province: "福建省", city: "龙岩", longitude: 117.02 },
  { province: "福建省", city: "宁德", longitude: 119.53 },
  { province: "江西省", city: "南昌", longitude: 115.89 },
  { province: "江西省", city: "景德镇", longitude: 117.21 },
  { province: "江西省", city: "萍乡", longitude: 113.85 },
  { province: "江西省", city: "九江", longitude: 116.0 },
  { province: "江西省", city: "新余", longitude: 114.93 },
  { province: "江西省", city: "鹰潭", longitude: 117.04 },
  { province: "江西省", city: "赣州", longitude: 114.93 },
  { province: "江西省", city: "吉安", longitude: 114.98 },
  { province: "江西省", city: "宜春", longitude: 114.38 },
  { province: "江西省", city: "抚州", longitude: 116.35 },
  { province: "江西省", city: "上饶", longitude: 117.95 },
  { province: "山东省", city: "济南", longitude: 116.98 },
  { province: "山东省", city: "青岛", longitude: 120.38 },
  { province: "山东省", city: "淄博", longitude: 118.05 },
  { province: "山东省", city: "枣庄", longitude: 117.55 },
  { province: "山东省", city: "东营", longitude: 118.67 },
  { province: "山东省", city: "烟台", longitude: 121.39 },
  { province: "山东省", city: "潍坊", longitude: 119.16 },
  { province: "山东省", city: "济宁", longitude: 116.59 },
  { province: "山东省", city: "泰安", longitude: 117.09 },
  { province: "山东省", city: "威海", longitude: 122.12 },
  { province: "山东省", city: "日照", longitude: 119.48 },
  { province: "山东省", city: "临沂", longitude: 118.35 },
  { province: "山东省", city: "德州", longitude: 116.31 },
  { province: "山东省", city: "聊城", longitude: 115.99 },
  { province: "山东省", city: "滨州", longitude: 118.02 },
  { province: "山东省", city: "菏泽", longitude: 115.47 },
  { province: "河南省", city: "郑州", longitude: 113.65 },
  { province: "河南省", city: "开封", longitude: 114.35 },
  { province: "河南省", city: "洛阳", longitude: 112.45 },
  { province: "河南省", city: "平顶山", longitude: 113.19 },
  { province: "河南省", city: "安阳", longitude: 114.39 },
  { province: "河南省", city: "鹤壁", longitude: 114.3 },
  { province: "河南省", city: "新乡", longitude: 113.92 },
  { province: "河南省", city: "焦作", longitude: 113.24 },
  { province: "河南省", city: "濮阳", longitude: 115.03 },
  { province: "河南省", city: "许昌", longitude: 113.85 },
  { province: "河南省", city: "漯河", longitude: 114.02 },
  { province: "河南省", city: "三门峡", longitude: 111.2 },
  { province: "河南省", city: "南阳", longitude: 112.53 },
  { province: "河南省", city: "商丘", longitude: 115.66 },
  { province: "河南省", city: "信阳", longitude: 114.08 },
  { province: "河南省", city: "周口", longitude: 114.65 },
  { province: "河南省", city: "驻马店", longitude: 114.03 },
  { province: "河南省", city: "济源", longitude: 112.59 },
  { province: "湖北省", city: "武汉", longitude: 114.29 },
  { province: "湖北省", city: "黄石", longitude: 115.06 },
  { province: "湖北省", city: "十堰", longitude: 110.79 },
  { province: "湖北省", city: "宜昌", longitude: 111.28 },
  { province: "湖北省", city: "襄阳", longitude: 112.12 },
  { province: "湖北省", city: "鄂州", longitude: 114.89 },
  { province: "湖北省", city: "荆门", longitude: 112.2 },
  { province: "湖北省", city: "孝感", longitude: 113.93 },
  { province: "湖北省", city: "荆州", longitude: 112.24 },
  { province: "湖北省", city: "黄冈", longitude: 114.88 },
  { province: "湖北省", city: "咸宁", longitude: 114.33 },
  { province: "湖北省", city: "随州", longitude: 113.37 },
  { province: "湖北省", city: "恩施", longitude: 109.48 },
  { province: "湖北省", city: "仙桃", longitude: 113.44 },
  { province: "湖北省", city: "潜江", longitude: 112.9 },
  { province: "湖北省", city: "天门", longitude: 113.17 },
  { province: "湖北省", city: "神农架", longitude: 110.67 },
  { province: "湖南省", city: "长沙", longitude: 112.93 },
  { province: "湖南省", city: "株洲", longitude: 113.14 },
  { province: "湖南省", city: "湘潭", longitude: 112.91 },
  { province: "湖南省", city: "衡阳", longitude: 112.57 },
  { province: "湖南省", city: "邵阳", longitude: 111.47 },
  { province: "湖南省", city: "岳阳", longitude: 113.13 },
  { province: "湖南省", city: "常德", longitude: 111.69 },
  { province: "湖南省", city: "张家界", longitude: 110.48 },
  { province: "湖南省", city: "益阳", longitude: 112.36 },
  { province: "湖南省", city: "郴州", longitude: 113.03 },
  { province: "湖南省", city: "永州", longitude: 111.61 },
  { province: "湖南省", city: "怀化", longitude: 109.96 },
  { province: "湖南省", city: "娄底", longitude: 111.99 },
  { province: "湖南省", city: "湘西", longitude: 109.74 },
  { province: "广东省", city: "广州", longitude: 113.26 },
  { province: "广东省", city: "韶关", longitude: 113.6 },
  { province: "广东省", city: "深圳", longitude: 114.06 },
  { province: "广东省", city: "珠海", longitude: 113.58 },
  { province: "广东省", city: "汕头", longitude: 116.68 },
  { province: "广东省", city: "佛山", longitude: 113.12 },
  { province: "广东省", city: "江门", longitude: 113.08 },
  { province: "广东省", city: "湛江", longitude: 110.36 },
  { province: "广东省", city: "茂名", longitude: 110.93 },
  { province: "广东省", city: "肇庆", longitude: 112.45 },
  { province: "广东省", city: "惠州", longitude: 114.41 },
  { province: "广东省", city: "梅州", longitude: 116.12 },
  { province: "广东省", city: "汕尾", longitude: 115.37 },
  { province: "广东省", city: "河源", longitude: 114.7 },
  { province: "广东省", city: "阳江", longitude: 111.98 },
  { province: "广东省", city: "清远", longitude: 113.06 },
  { province: "广东省", city: "东莞", longitude: 113.75 },
  { province: "广东省", city: "中山", longitude: 113.38 },
  { province: "广东省", city: "潮州", longitude: 116.63 },
  { province: "广东省", city: "揭阳", longitude: 116.35 },
  { province: "广东省", city: "云浮", longitude: 112.04 },
  { province: "广西壮族自治区", city: "南宁", longitude: 108.31 },
  { province: "广西壮族自治区", city: "柳州", longitude: 109.4 },
  { province: "广西壮族自治区", city: "桂林", longitude: 110.28 },
  { province: "广西壮族自治区", city: "梧州", longitude: 111.3 },
  { province: "广西壮族自治区", city: "北海", longitude: 109.11 },
  { province: "广西壮族自治区", city: "防城港", longitude: 108.35 },
  { province: "广西壮族自治区", city: "钦州", longitude: 108.63 },
  { province: "广西壮族自治区", city: "贵港", longitude: 109.59 },
  { province: "广西壮族自治区", city: "玉林", longitude: 110.16 },
  { province: "广西壮族自治区", city: "百色", longitude: 106.62 },
  { province: "广西壮族自治区", city: "贺州", longitude: 111.56 },
  { province: "广西壮族自治区", city: "河池", longitude: 108.06 },
  { province: "广西壮族自治区", city: "来宾", longitude: 109.22 },
  { province: "广西壮族自治区", city: "崇左", longitude: 107.35 },
  { province: "海南省", city: "海口", longitude: 110.35 },
  { province: "海南省", city: "三亚", longitude: 109.51 },
  { province: "海南省", city: "三沙", longitude: 112.34 },
  { province: "海南省", city: "儋州", longitude: 109.58 },
  { province: "重庆市", city: "重庆", longitude: 106.55 },
  { province: "四川省", city: "成都", longitude: 104.06 },
  { province: "四川省", city: "自贡", longitude: 104.77 },
  { province: "四川省", city: "攀枝花", longitude: 101.72 },
  { province: "四川省", city: "泸州", longitude: 105.44 },
  { province: "四川省", city: "德阳", longitude: 104.4 },
  { province: "四川省", city: "绵阳", longitude: 104.68 },
  { province: "四川省", city: "广元", longitude: 105.83 },
  { province: "四川省", city: "遂宁", longitude: 105.57 },
  { province: "四川省", city: "内江", longitude: 105.07 },
  { province: "四川省", city: "乐山", longitude: 103.77 },
  { province: "四川省", city: "南充", longitude: 106.11 },
  { province: "四川省", city: "眉山", longitude: 103.84 },
  { province: "四川省", city: "宜宾", longitude: 104.64 },
  { province: "四川省", city: "广安", longitude: 106.63 },
  { province: "四川省", city: "达州", longitude: 107.5 },
  { province: "四川省", city: "雅安", longitude: 103.0 },
  { province: "四川省", city: "巴中", longitude: 106.75 },
  { province: "四川省", city: "资阳", longitude: 104.65 },
  { province: "四川省", city: "阿坝", longitude: 102.22 },
  { province: "四川省", city: "甘孜", longitude: 101.96 },
  { province: "四川省", city: "凉山", longitude: 102.26 },
  { province: "贵州省", city: "贵阳", longitude: 106.71 },
  { province: "贵州省", city: "六盘水", longitude: 104.85 },
  { province: "贵州省", city: "遵义", longitude: 106.91 },
  { province: "贵州省", city: "安顺", longitude: 105.93 },
  { province: "贵州省", city: "毕节", longitude: 105.29 },
  { province: "贵州省", city: "铜仁", longitude: 109.19 },
  { province: "贵州省", city: "黔西南", longitude: 104.9 },
  { province: "贵州省", city: "黔东南", longitude: 108.31 },
  { province: "贵州省", city: "黔南", longitude: 107.52 },
  { province: "云南省", city: "昆明", longitude: 102.71 },
  { province: "云南省", city: "曲靖", longitude: 103.8 },
  { province: "云南省", city: "玉溪", longitude: 102.54 },
  { province: "云南省", city: "保山", longitude: 99.17 },
  { province: "云南省", city: "昭通", longitude: 103.72 },
  { province: "云南省", city: "丽江", longitude: 100.23 },
  { province: "云南省", city: "普洱", longitude: 101.0 },
  { province: "云南省", city: "临沧", longitude: 100.09 },
  { province: "云南省", city: "楚雄", longitude: 101.54 },
  { province: "云南省", city: "红河", longitude: 103.4 },
  { province: "云南省", city: "文山", longitude: 104.24 },
  { province: "云南省", city: "西双版纳", longitude: 100.8 },
  { province: "云南省", city: "大理", longitude: 100.27 },
  { province: "云南省", city: "德宏", longitude: 98.58 },
  { province: "云南省", city: "怒江", longitude: 98.85 },
  { province: "云南省", city: "迪庆", longitude: 99.71 },
  { province: "西藏自治区", city: "拉萨", longitude: 91.11 },
  { province: "西藏自治区", city: "日喀则", longitude: 88.89 },
  { province: "西藏自治区", city: "昌都", longitude: 97.18 },
  { province: "西藏自治区", city: "林芝", longitude: 94.36 },
  { province: "西藏自治区", city: "山南", longitude: 91.77 },
  { province: "西藏自治区", city: "那曲", longitude: 92.07 },
  { province: "西藏自治区", city: "阿里", longitude: 80.1 },
  { province: "陕西省", city: "西安", longitude: 108.94 },
  { province: "陕西省", city: "铜川", longitude: 108.94 },
  { province: "陕西省", city: "宝鸡", longitude: 107.24 },
  { province: "陕西省", city: "咸阳", longitude: 108.7 },
  { province: "陕西省", city: "渭南", longitude: 109.5 },
  { province: "陕西省", city: "延安", longitude: 109.49 },
  { province: "陕西省", city: "汉中", longitude: 107.03 },
  { province: "陕西省", city: "榆林", longitude: 109.74 },
  { province: "陕西省", city: "安康", longitude: 108.91 },
  { province: "陕西省", city: "商洛", longitude: 109.94 },
  { province: "甘肃省", city: "兰州", longitude: 103.82 },
  { province: "甘肃省", city: "嘉峪关", longitude: 98.29 },
  { province: "甘肃省", city: "金昌", longitude: 102.19 },
  { province: "甘肃省", city: "白银", longitude: 104.14 },
  { province: "甘肃省", city: "天水", longitude: 105.72 },
  { province: "甘肃省", city: "武威", longitude: 102.64 },
  { province: "甘肃省", city: "张掖", longitude: 100.45 },
  { province: "甘肃省", city: "平凉", longitude: 106.68 },
  { province: "甘肃省", city: "酒泉", longitude: 98.51 },
  { province: "甘肃省", city: "庆阳", longitude: 107.64 },
  { province: "甘肃省", city: "定西", longitude: 104.6 },
  { province: "甘肃省", city: "陇南", longitude: 104.92 },
  { province: "甘肃省", city: "临夏", longitude: 103.21 },
  { province: "甘肃省", city: "甘南", longitude: 102.91 },
  { province: "青海省", city: "西宁", longitude: 101.77 },
  { province: "青海省", city: "海东", longitude: 102.11 },
  { province: "青海省", city: "海北", longitude: 100.9 },
  { province: "青海省", city: "黄南", longitude: 102.02 },
  { province: "青海省", city: "海南州", longitude: 100.62 },
  { province: "青海省", city: "果洛", longitude: 100.24 },
  { province: "青海省", city: "玉树", longitude: 97.01 },
  { province: "青海省", city: "海西", longitude: 97.34 },
  { province: "宁夏回族自治区", city: "银川", longitude: 106.27 },
  { province: "宁夏回族自治区", city: "石嘴山", longitude: 106.39 },
  { province: "宁夏回族自治区", city: "吴忠", longitude: 106.2 },
  { province: "宁夏回族自治区", city: "固原", longitude: 106.28 },
  { province: "宁夏回族自治区", city: "中卫", longitude: 105.19 },
  { province: "新疆维吾尔自治区", city: "乌鲁木齐", longitude: 87.61 },
  { province: "新疆维吾尔自治区", city: "克拉玛依", longitude: 84.87 },
  { province: "新疆维吾尔自治区", city: "吐鲁番", longitude: 89.19 },
  { province: "新疆维吾尔自治区", city: "哈密", longitude: 93.52 },
  { province: "新疆维吾尔自治区", city: "昌吉", longitude: 87.3 },
  { province: "新疆维吾尔自治区", city: "博尔塔拉", longitude: 82.07 },
  { province: "新疆维吾尔自治区", city: "巴音郭楞", longitude: 86.15 },
  { province: "新疆维吾尔自治区", city: "阿克苏", longitude: 80.27 },
  { province: "新疆维吾尔自治区", city: "克孜勒苏", longitude: 76.17 },
  { province: "新疆维吾尔自治区", city: "喀什", longitude: 75.99 },
  { province: "新疆维吾尔自治区", city: "和田", longitude: 79.93 },
  { province: "新疆维吾尔自治区", city: "伊犁", longitude: 81.32 },
  { province: "新疆维吾尔自治区", city: "塔城", longitude: 83.0 },
  { province: "新疆维吾尔自治区", city: "阿勒泰", longitude: 88.14 },
  { province: "香港特别行政区", city: "香港", longitude: 114.17 },
  { province: "澳门特别行政区", city: "澳门", longitude: 113.55 },
  { province: "台湾省", city: "台北", longitude: 121.56 },
  { province: "台湾省", city: "新北", longitude: 121.47 },
  { province: "台湾省", city: "桃园", longitude: 121.3 },
  { province: "台湾省", city: "台中", longitude: 120.67 },
  { province: "台湾省", city: "台南", longitude: 120.2 },
  { province: "台湾省", city: "高雄", longitude: 120.3 },
  { province: "台湾省", city: "基隆", longitude: 121.74 },
];

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.email) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const adminEmails = ["841428951@qq.com"];
  if (!adminEmails.includes(session.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const cities = await prisma.city.findMany({
    orderBy: [{ province: "asc" }, { city: "asc" }],
  });
  return NextResponse.json(cities);
}

// 初始化/批量添加城市数据
export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.email) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const adminEmails = ["841428951@qq.com"];
  if (!adminEmails.includes(session.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const body = await req.json();
  const { action } = body;

  if (action === "init") {
    // 批量初始化所有城市数据
    const result = await prisma.city.createMany({
      data: DEFAULT_CITIES.map((c) => ({
        province: c.province,
        city: c.city,
        longitude: c.longitude,
        timezone: "Asia/Shanghai",
      })),
      skipDuplicates: true,
    });
    return NextResponse.json({ ok: true, count: result.count });
  }

  if (action === "add") {
    const { province, city, longitude } = body;
    if (!province || !city || longitude === undefined) {
      return NextResponse.json({ error: "缺少必填字段" }, { status: 400 });
    }
    const result = await prisma.city.create({
      data: { province, city, longitude, timezone: "Asia/Shanghai" },
    });
    return NextResponse.json({ ok: true, city: result });
  }

  return NextResponse.json({ error: "未知操作" }, { status: 400 });
}

// 删除城市
export async function DELETE(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.email) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const adminEmails = ["841428951@qq.com"];
  if (!adminEmails.includes(session.user.email)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const id = req.nextUrl.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 });
  await prisma.city.delete({ where: { id } });
  return NextResponse.json({ ok: true });
}
